on: workflow_dispatch
jobs:
  dispatch:
    name: Dispatcher
    runs-on: ubuntu-latest
    steps:
    - name: Trigger end to end tests
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/dispatches \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'Accept: application/vnd.github.v3+json' \
        --data '{
          "event_type": "deployed"
          }'
