on:
  schedule:
  - cron : 0 0 * * *
  workflow_dispatch:
jobs:
  api:
    name: API tests

    runs-on: ubuntu-latest

    env:
      DEFAULT_BRANCH: master
      NODE_VERSION: 14.x

    steps:
    - name: Checkout to branch ${{ env.DEFAULT_BRANCH }}
      uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm ci
    - run: npm run test:api
    - name: Upload results to S3
      uses: shallwefootball/s3-upload-action@v1.1.3
      with:
        aws_key_id: ${{ secrets.AWS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws_bucket: ${{ secrets.AWS_BUCKET }}
        source_dir: 'mochawesome-report'

    
  ui:
    name: UI tests

    runs-on: ubuntu-latest

    env:
      DEFAULT_BRANCH: master
      NODE_VERSION: 14.x

    steps:
    - name: Checkout to branch ${{ env.DEFAULT_BRANCH }}
      uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm ci
    - run: docker-compose up -d
    - run: npm run test:ui
    - name: Upload results to S3
      uses: shallwefootball/s3-upload-action@v1.1.3
      with:
        aws_key_id: ${{ secrets.AWS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws_bucket: ${{ secrets.AWS_BUCKET }}
        source_dir: 'mochawesome-reports'
